import React, { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { event, sections, sectionById, stages } from './workshopData.js';
import WorkshopVisual from './Visuals.jsx';

const WORLD={width:1600,height:920};
const positions=[[175,238],[460,194],[735,244],[1010,195],[1315,252],[1290,492],[805,492],[323,492],[260,738],[775,734],[1290,738]];
function Icon({name,size=20}) {
  const paths={map:<><path d="M3 6.5 9 4l6 2.5L21 4v13.5L15 20l-6-2.5L3 20z"/><path d="M9 4v13.5M15 6.5V20"/></>,plus:<path d="M12 5v14M5 12h14"/>,minus:<path d="M5 12h14"/>,fit:<><path d="M8 3H4a1 1 0 0 0-1 1v4M16 3h4a1 1 0 0 1 1 1v4M3 16v4a1 1 0 0 0 1 1h4M21 16v4a1 1 0 0 1-1 1h-4"/></>,arrow:<path d="M5 12h14m-6-6 6 6-6 6"/>,back:<path d="M19 12H5m6-6-6 6 6 6"/>,screen:<><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8m-4-4v4"/></>,check:<path d="m4 12 5 5L20 6"/>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
function routeFromHash(){const match=window.location.hash.match(/^#\/seccion\/(\d{1,2})$/);const id=match?.[1]?.padStart(2,'0');return id&&sectionById[id]?id:null;}
function useReducedMotion(){const [reduced,setReduced]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches);useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);return reduced;}
function Progress({current,completed}){return <div className="progress" aria-label={`${completed.length} de 11 secciones visitadas`}><div className="progress-track"><span style={{width:`${completed.length/11*100}%`}}/></div><span>{current?`${Number(current)} / 11`:`${completed.length} / 11 visitadas`}</span></div>;}

function MapView({onOpen,completed,current,reduced}){
  const viewport=useRef(null),pointers=useRef(new Map()),gesture=useRef(null),interacted=useRef(false);
  const [view,setView]=useState({x:0,y:0,scale:.7}),[selected,setSelected]=useState(Math.max(0,sections.findIndex(s=>s.id===current))),[mobileVisual,setMobileVisual]=useState(false);
  const fit=useCallback(()=>{const el=viewport.current;if(!el)return;const {width,height}=el.getBoundingClientRect();const scale=Math.min((width-58)/WORLD.width,(height-24)/WORLD.height,1.15);setView({scale,x:(width-WORLD.width*scale)/2,y:(height-WORLD.height*scale)/2});interacted.current=false;},[]);
  useLayoutEffect(()=>{fit();const observer=new ResizeObserver(()=>{if(!interacted.current)fit();});if(viewport.current)observer.observe(viewport.current);return()=>observer.disconnect();},[fit]);
  const zoomAt=useCallback((factor,cx,cy)=>{interacted.current=true;setView(old=>{const scale=Math.max(.38,Math.min(2.2,old.scale*factor)),ratio=scale/old.scale;return{scale,x:cx-(cx-old.x)*ratio,y:cy-(cy-old.y)*ratio};});},[]);
  const zoomCenter=factor=>{const rect=viewport.current?.getBoundingClientRect();if(rect)zoomAt(factor,rect.width/2,rect.height/2);};
  const openNode=index=>{setSelected(index);const el=viewport.current,[px,py]=positions[index];if(el&&!reduced){const {width,height}=el.getBoundingClientRect(),scale=Math.max(1.25,Math.min(1.7,width/950));setView({scale,x:width/2-px*scale,y:height/2-py*scale});window.setTimeout(()=>onOpen(sections[index].id),270);}else onOpen(sections[index].id);};
  const onPointerDown=e=>{if(e.target.closest('button'))return;e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.current.size===2){const[a,b]=[...pointers.current.values()];gesture.current={distance:Math.hypot(a.x-b.x,a.y-b.y),view};}};
  const onPointerMove=e=>{const old=pointers.current.get(e.pointerId);if(!old)return;pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});interacted.current=true;if(pointers.current.size===1)setView(v=>({...v,x:v.x+e.clientX-old.x,y:v.y+e.clientY-old.y}));else if(pointers.current.size===2){const[a,b]=[...pointers.current.values()],distance=Math.hypot(a.x-b.x,a.y-b.y),start=gesture.current;if(!start)return;const rect=viewport.current.getBoundingClientRect(),cx=(a.x+b.x)/2-rect.left,cy=(a.y+b.y)/2-rect.top,scale=Math.max(.38,Math.min(2.2,start.view.scale*distance/start.distance)),ratio=scale/start.view.scale;setView({scale,x:cx-(cx-start.view.x)*ratio,y:cy-(cy-start.view.y)*ratio});}};
  const onPointerUp=e=>{pointers.current.delete(e.pointerId);if(pointers.current.size<2)gesture.current=null;};
  useEffect(()=>{const el=viewport.current;if(!el)return;const onWheel=e=>{e.preventDefault();const rect=el.getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*.001),e.clientX-rect.left,e.clientY-rect.top);};el.addEventListener('wheel',onWheel,{passive:false});return()=>el.removeEventListener('wheel',onWheel);},[zoomAt]);
  const onMapKey=e=>{if(e.target!==viewport.current)return;if(['ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();setSelected(i=>Math.min(10,i+1));}if(['ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();setSelected(i=>Math.max(0,i-1));}if(e.key==='Enter'){e.preventDefault();openNode(selected);}if(e.key==='+'||e.key==='='){e.preventDefault();zoomCenter(1.2);}if(e.key==='-'){e.preventDefault();zoomCenter(1/1.2);}if(e.key==='0'||e.key==='Home'){e.preventDefault();fit();}};
  return <main className="map-page"><div className="map-intro"><div><p className="eyebrow">{event.name} <span>/</span> {event.subtitle}</p><h1>Inferencia de LLMs<br/><em>en local.</em></h1><p>De cargar los primeros pesos a servir peticiones con criterio.</p><div className="map-intro-actions"><button className="hero-start" onClick={()=>onOpen('01')}><span className="hero-start-long">Empezar el taller</span><span className="hero-start-short">Empezar</span><Icon name="arrow" size={20}/></button><span>O entra por cualquier parada del mapa.</span></div><a className="event-link" href={event.url} target="_blank" rel="noreferrer">{event.date} · {event.place} <span aria-hidden="true">↗</span></a></div><div className="map-intro-side"><span>TALLER · GDG VALLADOLID</span><strong>Eduardo Zapatero<br/>Álvaro García Pizarro <small>@lvrpiz</small></strong><p>11 secciones · 3 etapas</p></div></div>
    <div className={'map-area '+(mobileVisual?'show-mobile-visual':'')}><div className="map-viewport" ref={viewport} tabIndex={0} role="group" aria-label="Mapa del taller. Flechas para elegir, Intro para abrir, más y menos para zoom, cero para ajustar." onKeyDown={onMapKey} onPointerDown={onPointerDown} onPointerMove={onPointerMove} onPointerUp={onPointerUp} onPointerCancel={onPointerUp}><div className="map-world" style={{width:WORLD.width,height:WORLD.height,transform:`translate(${view.x}px, ${view.y}px) scale(${view.scale})`,transition:reduced||interacted.current?'none':'transform 270ms cubic-bezier(.2,.8,.2,1)'}}><div className="stage-band fundamentals"><span>01 / FUNDAMENTOS</span><small>Del texto a los pesos</small></div><div className="stage-band serving"><span>02 / SERVICIO</span><small>De una petición a muchas</small></div><div className="stage-band production"><span>03 / PRODUCCIÓN</span><small>De la GPU al servicio</small></div><svg className="map-links" width="1600" height="920" viewBox="0 0 1600 920" aria-hidden="true"><path d="M175 238 C280 170 355 170 460 194 S630 250 735 244 S905 150 1010 195 S1220 230 1315 252 C1460 350 1415 425 1290 492 C1120 555 985 500 805 492 S490 475 323 492 C145 550 130 685 260 738 C420 805 580 720 775 734 S1110 705 1290 738"/></svg>{sections.map((section,index)=>{const[x,y]=positions[index];return <button key={section.id} type="button" className={'map-node '+(current===section.id?'current ':'')+(selected===index?'selected ':'')+(completed.includes(section.id)?'done':'')} style={{left:x,top:y}} onClick={()=>openNode(index)} aria-label={`Sección ${Number(section.id)}: ${section.title}${completed.includes(section.id)?', visitada':''}`}><span className="node-number">{section.id}</span><span className="node-label">{section.short}</span><span className="node-status">{completed.includes(section.id)?<Icon name="check" size={15}/>:<Icon name="arrow" size={16}/>}</span></button>;})}</div></div><div className="map-tools"><button onClick={()=>zoomCenter(1.25)} aria-label="Acercar mapa" title="Acercar"><Icon name="plus"/></button><button onClick={()=>zoomCenter(.8)} aria-label="Alejar mapa" title="Alejar"><Icon name="minus"/></button><button onClick={fit} aria-label="Ajustar mapa a la pantalla" title="Ajustar"><Icon name="fit"/></button></div><div className="map-hint">Selecciona una parada · Arrastra para mover el mapa</div><div className="mobile-map-toggle"><button onClick={()=>setMobileVisual(v=>!v)}>{mobileVisual?'Ver lista':'Ver mapa visual'}</button></div><div className="mobile-map-list"><SectionList onOpen={onOpen} completed={completed}/></div></div>
    <details className="map-index"><summary>Lista de secciones <span>↗</span></summary><SectionList onOpen={onOpen} completed={completed}/></details>
  </main>;
}
function SectionList({onOpen,completed}){return <ol className="section-list">{stages.map(stage=><li key={stage.id}><h3>{stage.name}<small>{stage.range}</small></h3><ol>{sections.filter(s=>s.stage===stage.id).map(s=><li key={s.id}><button onClick={()=>onOpen(s.id)}><span>{s.id}</span>{s.title}{completed.includes(s.id)&&<Icon name="check" size={16}/>}</button></li>)}</ol></li>)}</ol>;}

function SectionView({section,presentation,onNext,onMap}){
  const index=sections.findIndex(s=>s.id===section.id),stage=stages.find(s=>s.id===section.stage),scrollRef=useRef(null);
  useEffect(()=>{scrollRef.current?.scrollTo({top:0,behavior:'instant'});},[section.id]);
  return <main className={'section-page '+(presentation?'is-presenting':'')} ref={scrollRef}><div className="section-inner"><div className="opening-moment"><div className="section-overline"><span>{stage.name}</span><span>{section.id} / 11</span></div><div className="section-hero"><div><p className="section-kicker">{stage.range}</p><h1>{section.title}</h1><p className="section-lead">{section.lead}</p></div><span className="hero-index" aria-hidden="true">{section.id}</span></div><div className="hero-idea"><span>LA IDEA CLAVE</span><strong>{section.idea}</strong></div></div><div className="diagram-moment"><WorkshopVisual key={section.id} type={section.visual}/></div>
    <section className="story-section" aria-label="Explicación"><div className="story-heading"><p className="block-label">Vamos por partes</p><h2>{section.storyHeading}</h2></div><div className="story-list">{section.story.map((block,i)=><article className="story-block" key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{block.title}</h3><p>{block.text}</p></div></article>)}</div></section>
    <section className="takeaways" aria-label="Puntos para recordar"><p className="block-label">Para llevarse</p><ul>{section.points.map((point,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{point}</li>)}</ul></section>
    {section.decisions&&<section className="final-decisions"><div><p className="block-label">Ejercicio final</p><h2>Las siete decisiones</h2><p>Usad las cifras anteriores como punto de partida. La decisión se valida con medidas.</p></div><ol>{section.decisions.map((item,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{item}</li>)}</ol></section>}
    {section.notebook&&<div className="notebook-cue"><div><span>SIGUIENTE PASO · CUADERNO PRÁCTICO</span><strong>{section.notebook}</strong>{section.footnote&&<p>{section.footnote}</p>}</div><Icon name="arrow" size={30}/></div>}
    <div className="section-bottom"><button onClick={onMap}>Volver al mapa</button>{index<10&&<button className="next-bottom" onClick={onNext}>Siguiente sección <Icon name="arrow" size={18}/></button>}</div>
  </div></main>;
}

export default function App(){
  const [sectionId,setSectionId]=useState(routeFromHash),[presentation,setPresentation]=useState(false),[completed,setCompleted]=useState(()=>{try{return JSON.parse(sessionStorage.getItem('gdg-completed')||'[]');}catch{return[];}});
  const reduced=useReducedMotion();
  useEffect(()=>{const update=()=>{const route=routeFromHash();setSectionId(route);if(!route)setPresentation(false);};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
  useEffect(()=>{sessionStorage.setItem('gdg-completed',JSON.stringify(completed));},[completed]);
  useEffect(()=>{if(sectionId)setCompleted(old=>old.includes(sectionId)?old:[...old,sectionId]);},[sectionId]);
  const openSection=id=>{setSectionId(id);window.location.hash=`/seccion/${id}`;};
  const showMap=()=>{setPresentation(false);setSectionId(null);window.location.hash='/mapa';};
  const move=delta=>{if(!sectionId)return;const index=sections.findIndex(s=>s.id===sectionId);openSection(sections[Math.max(0,Math.min(10,index+delta))].id);};
  useEffect(()=>{const onKey=e=>{if(e.key==='Escape'&&presentation){showMap();return;}if(e.target instanceof HTMLElement&&e.target.closest('input, textarea, select, summary, [contenteditable="true"], .interactive-visual button'))return;if(presentation&&sectionId){if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();move(-1);}}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
  const section=sectionId?sectionById[sectionId]:null;
  return <div className={'app '+(presentation?'presentation':'')}><header className="site-header"><button className="brand" onClick={showMap} aria-label="Ir al mapa del taller"><img className="brand-mark" src="/gdg-icon.svg" alt=""/><span>VallaTech Summit <b>/</b> Inferencia local</span></button><div className="header-actions">{section&&<button className="header-map" onClick={showMap}><Icon name="map" size={18}/> <span>Mapa</span></button>}<button className="presentation-trigger" aria-label={presentation?'Salir de presentación y volver al mapa':'Entrar en modo presentación'} onClick={()=>{if(presentation){showMap();return;}if(!sectionId)openSection('01');setPresentation(true);}}><Icon name="screen" size={18}/><span>{presentation?'Salir al mapa':'Presentar'}</span></button></div></header><div className="workspace">{section?<SectionView section={section} presentation={presentation} onNext={()=>move(1)} onMap={showMap}/>:<MapView onOpen={openSection} completed={completed} current={completed.at(-1)} reduced={reduced}/>}</div>{section?<nav className="presentation-nav" aria-label="Navegación de secciones"><button onClick={()=>move(-1)} disabled={section.id==='01'}><Icon name="back" size={18}/><span>Anterior</span></button><Progress current={section.id} completed={completed}/><button onClick={()=>move(1)} disabled={section.id==='11'}><span>Siguiente</span><Icon name="arrow" size={18}/></button></nav>:<div className="overview-footer"><span>El recorrido completo, de los pesos a producción.</span><Progress current={null} completed={completed}/><span className="footer-hint">Elige una parada para abrirla</span></div>}</div>;
}
