export const event = {
  name: 'VallaTech Summit 2026',
  subtitle: 'DevFest Valladolid',
  date: '13 de noviembre de 2026',
  place: 'Escuela de Ingeniería Informática · Universidad de Valladolid',
  url: 'https://gdg.community.dev/events/details/google-gdg-valladolid-presents-vallatech-summit-2026-devfest-valladolid/',
};

export const stages = [
  { id: 'fundamentos', name: '01 / Fundamentos', range: 'Entender qué cargamos y cuánto ocupa' },
  { id: 'servicio', name: '02 / Servicio', range: 'Atender peticiones y medir' },
  { id: 'produccion', name: '03 / Producción', range: 'Operar, repartir y dimensionar' },
];

export const sections = [
  {
    id: '01', stage: 'fundamentos', title: '¿Qué significa ejecutar un LLM?', short: 'Ejecutar un LLM', visual: 'flow',
    storyHeading: 'De la frase al siguiente token',
    lead: 'Escribes una frase. ¿Qué tiene que pasar para que el modelo escriba la siguiente?',
    idea: 'Inferir es generar con unos pesos ya entrenados. Entrenar cambia esos pesos.',
    points: ['Una API de proveedor ejecuta el modelo en su infraestructura; si cargas los pesos, eliges el runtime y asumes la operación.', 'El paquete suele traer pesos, tokenizer, configuración, arquitectura y plantilla de chat.', '«Pesos abiertos» no dice por sí solo qué permite la licencia.'],
    story: [
      { title: 'La petición no llega como texto', text: 'El tokenizer parte el prompt en tokens. El modelo calcula puntuaciones para el siguiente token (logits); el muestreo escoge uno. Se repite hasta detener la generación. Si cambias el tokenizer o la plantilla de chat sin comprobar el checkpoint, la entrada puede dejar de significar lo que creías.' },
      { title: 'API o pesos en tu infraestructura', text: 'Con una API envías la petición y recibes la respuesta. Al cargar pesos eliges cómo servirlos, cuánto contexto permitir y qué GPU usar. Ganar control también significa ocuparse de memoria, versiones y fallos.' },
      { title: 'Cinco nombres que verás enseguida', text: 'Hugging Face aloja modelos y sus fichas. Transformers permite cargarlos y experimentar en código. llama.cpp es habitual en inferencia local y GGUF. Ollama simplifica la puesta en marcha. vLLM se centra en servir peticiones concurrentes.' },
    ],
    notebook: 'Notebook 01 · Primera inferencia, tokenizer y generación',
  },
  {
    id: '02', stage: 'fundamentos', title: 'Tamaño, parámetros y arquitectura', short: 'Tamaño y arquitectura', visual: 'architecture',
    storyHeading: 'Dentro del modelo',
    lead: 'Dos modelos pueden tener el mismo número de parámetros y comportarse de forma muy distinta.',
    idea: 'Los parámetros hablan del modelo. El contexto habla de cuántos tokens caben en una petición.',
    points: ['1B, 3B, 7B, 14B, 32B y 70B son miles de millones de parámetros, aproximadamente.', 'Más parámetros suelen exigir más memoria y cálculo. La calidad depende también de los datos, la arquitectura y la tarea.', 'En MoE importa separar parámetros totales de parámetros activos por token.'],
    story: [
      { title: 'Qué hay dentro de un decoder', text: 'Un decoder apila bloques con atención y una red feed-forward. El número de capas indica cuántas veces se repite el bloque; hidden size es la anchura de la representación. Las attention heads reparten la atención y las KV heads determinan parte del estado que se conserva durante la generación.' },
      { title: 'Dense y MoE hacen cuentas distintas', text: 'En un modelo Dense interviene el bloque principal de pesos en cada token. Un Mixture of Experts usa un router para activar algunos expertos. Los pesos que residen en memoria dependen del total cargado; el cómputo por token depende, entre otras cosas, de los expertos elegidos.' },
      { title: 'La ventana también se llena', text: 'Prompt y respuesta comparten el presupuesto de contexto. Si admites 4.096 tokens y el prompt ocupa 3.800, quedan pocos para la respuesta. El tamaño en B no te dice cuánta ventana tiene el modelo.' },
    ],
  },
  {
    id: '03', stage: 'fundamentos', title: 'Precisión y cuantización', short: 'Precisión y cuantización', visual: 'precision',
    storyHeading: 'Bits, formatos y calidad',
    lead: 'Menos bits reducen la cuenta ideal de los pesos. Lo que ocurra al ejecutar el modelo hay que medirlo.',
    idea: 'Peso más pequeño no significa automáticamente respuesta más rápida.',
    points: ['FP32: 4 bytes por parámetro. FP16/BF16: 2. FP8/INT8: cerca de 1. INT4: cerca de 0,5.', 'Estas cifras no incluyen escalas, metadatos, tensores sin cuantizar ni memoria del runtime.', 'Calidad, kernels, GPU y formato cambian el resultado práctico.'],
    story: [
      { title: 'Qué se gana y qué se arriesga', text: 'La cuantización aproxima los valores con menos precisión. Suele ahorrar memoria de pesos. Puede cambiar la calidad, sobre todo en tareas sensibles, y no todas las GPU tienen kernels igual de buenos para cada representación.' },
      { title: 'Cuatro etiquetas, cuatro preguntas', text: 'GGUF es un formato de archivo y metadatos habitual en el ecosistema llama.cpp. AWQ y GPTQ nombran métodos de cuantización posentrenamiento. FP8 es una representación numérica. Mezclarlas como si fuesen alternativas equivalentes oculta lo que hay que comprobar.' },
      { title: 'La comparación útil', text: 'Compara dos variantes del mismo modelo con los mismos prompts y parámetros de generación. Mira memoria, calidad y tiempo. Si una variante ahorra VRAM pero empeora las respuestas que necesitas, la cifra de bits no resuelve tu problema.' },
    ],
    notebook: 'Notebook 02 · Comparar dos variantes del mismo modelo',
  },
  {
    id: '04', stage: 'fundamentos', title: 'Estimar la VRAM', short: 'Estimar la VRAM', visual: 'memory',
    storyHeading: 'Una cuenta, varias partidas',
    lead: 'Empieza por los pesos. Luego añade todo lo que la primera multiplicación deja fuera.',
    idea: 'Memoria de pesos ≈ parámetros × bytes por parámetro.',
    points: ['8B × 2 bytes ≈ 16 GB decimales, unos 14,9 GiB de pesos.', 'La KV cache crece con los tokens residentes y las secuencias activas.', 'Activaciones, buffers, runtime, CUDA graphs y margen también cuentan.'],
    story: [
      { title: 'La cuenta que cabe en una servilleta', text: 'Un modelo de 8B en FP16 necesita cerca de 16 GB decimales solo para pesos. Pasado a unidades binarias son unos 14,9 GiB. Ninguna de las dos cifras es la VRAM total del proceso.' },
      { title: 'La caché que aparece al conversar', text: 'Para un Transformer/GQA estándar, una aproximación es: 2 × capas × KV heads × dimensión de cada head × bytes por elemento × tokens residentes. Si crecen el contexto o las conversaciones activas, suele crecer esta partida.' },
      { title: 'Ejemplo, con arquitectura supuesta', text: 'Con 32 capas, 8 KV heads, dimensión 128 y FP16 salen unos 128 KiB por token. Una secuencia de 4.096 tokens ronda 512 MiB; ocho iguales, cerca de 4 GiB. MLA y la atención de ventana deslizante requieren otra cuenta.' },
      { title: 'La GPU puede mostrar otra cifra', text: 'La arquitectura, los metadatos, los pools reservados por el runtime y los ajustes de ejecución cambian la memoria observada. Mide después de cargar y bajo una carga parecida a la real; deja margen para los picos.' },
    ],
    notebook: 'Notebook 03 · Calcular, cargar y comparar memoria teórica y observada',
  },
  {
    id: '05', stage: 'fundamentos', title: 'Elegir un modelo', short: 'Elegir un modelo', visual: 'decision',
    storyHeading: 'Del caso de uso a la prueba',
    lead: 'El ranking te da candidatos. La prueba con tus propios ejemplos decide si alguno sirve.',
    idea: 'Primero la tarea; después el checkpoint concreto y sus condiciones de uso.',
    points: ['Especifica idioma, calidad, contexto y uso de herramientas.', 'Lee licencia, model card, configuración, tokenizer y plantilla de chat.', 'Calcula pesos, KV cache y runtime antes de probar la carga.'],
    story: [
      { title: 'Escribe el caso de uso en una frase', text: '«Responder preguntas de soporte en castellano con documentos de 3.000 tokens» ya permite discutir calidad, idioma y contexto. «Quiero un modelo potente» todavía no ayuda a elegir.' },
      { title: 'Descarta con pruebas, no con intuición', text: 'Compara arquitectura Dense o MoE, parámetros, licencia y variantes de precisión. Comprueba que modelo, GPU, runtime y kernels funcionan juntos. La ficha del modelo y sus condiciones de benchmark son parte de la lectura.' },
      { title: 'Haz una lista corta', text: 'Un benchmark público puede servir para filtrar. Después evalúa con prompts representativos de tu tarea y anota por qué descartaste el otro candidato. En grupos, elegid un caso de uso, una GPU y un contexto; defended vuestra elección y un descarte.' },
    ],
  },
  {
    id: '06', stage: 'servicio', title: 'Transformers, vLLM y servicio', short: 'Del modelo al servicio', visual: 'serving',
    storyHeading: 'Una GPU, varias peticiones',
    lead: 'Una generación aislada y una API con peticiones simultáneas plantean problemas distintos.',
    idea: 'Cliente → API → scheduler → motor de inferencia + GPU.',
    points: ['Transformers da acceso directo al modelo y control de generación durante el desarrollo.', 'vLLM añade scheduling, gestión de KV cache y lotes continuos para servir peticiones.', 'Su endpoint puede hablar con clientes de estilo OpenAI.'],
    story: [
      { title: 'Cuando estás experimentando', text: 'Con Transformers cargas el modelo, inspeccionas entradas y cambias la generación desde código. Es una buena forma de entender el comportamiento de un checkpoint.' },
      { title: 'Cuando llegan varias personas', text: 'vLLM organiza peticiones concurrentes. El scheduler decide qué entra en cada iteración y gestiona memoria para secuencias activas. Transformers y vLLM pueden convivir en el mismo proyecto.' },
      { title: 'El lote no tiene que esperar a todos', text: 'En los lotes continuos una petición nueva puede incorporarse mientras otras siguen generando; una terminada deja sitio. El esquema enseña la mecánica, no promete una mejora concreta de rendimiento.' },
    ],
    notebook: 'Notebook 04 · Generar con vLLM y llamar a su endpoint',
  },
  {
    id: '07', stage: 'servicio', title: 'Métricas de rendimiento', short: 'Medir el servicio', visual: 'metrics',
    storyHeading: 'Dos maneras de ir rápido',
    lead: '«Va rápido» suele esconder dos preguntas: cuánto espera una persona y cuánto trabajo termina el sistema.',
    idea: 'Un throughput alto puede convivir con una cola larga.',
    points: ['TTFT: hasta el primer token. ITL: intervalo entre tokens. TPOT: promedio por token de salida tras el primero, si se usa esa definición.', 'Mide también latencia completa, tokens de salida/s, peticiones terminadas/s, concurrencia, cola y errores.', 'Compara percentiles, no solo promedios.'],
    story: [
      { title: 'Lo que nota quien pregunta', text: 'El TTFT recoge la espera hasta ver el primer token. El ITL describe el ritmo al que llegan los siguientes. La latencia end-to-end acaba cuando termina la respuesta entera.' },
      { title: 'Lo que necesita quien opera', text: 'Tokens de salida por segundo y peticiones completadas por segundo describen trabajo agregado. Con más usuarios puedes procesar más en total y, al mismo tiempo, hacer esperar más a cada uno.' },
      { title: 'Una comparación que sí sirve', text: 'Usa el mismo modelo, GPU, prompts, longitudes de salida y sampling. Calienta el sistema, repite, registra errores y comunica percentiles. Prueba 1, 10 y 50 concurrentes si te sirven como puntos de exploración; no son cifras de capacidad.' },
    ],
    notebook: 'Notebook 05 · Medir concurrencia y detectar cuándo la cola rompe el objetivo',
  },
  {
    id: '08', stage: 'servicio', title: 'Ajustar vLLM', short: 'Ajustar vLLM', visual: 'tuning',
    storyHeading: 'Qué toca cada ajuste',
    lead: 'Cada ajuste mueve un límite. Sin línea base, no sabrás si el cambio ayudó.',
    idea: 'Cambia una o dos cosas, mide y conserva solo lo que mejora tu objetivo.',
    points: ['gpu-memory-utilization y max-model-len condicionan el presupuesto de memoria y contexto.', 'max-num-seqs y max-num-batched-tokens cambian el trabajo admitido por el scheduler.', 'Prefijos compartidos, prefill largo y CUDA graphs tienen ventajas y costes propios.'],
    story: [
      { title: 'Memoria y tamaño de petición', text: 'Un max-model-len más largo admite entradas mayores y puede aumentar la demanda potencial de KV cache. gpu-memory-utilization orienta el presupuesto de memoria que usa vLLM. Deja margen para el resto del proceso.' },
      { title: 'El scheduler también tiene límites', text: 'Más secuencias pueden mejorar el throughput, pero presionan memoria y latencia. max-num-batched-tokens limita tokens por lote. La longitud real de prompts y respuestas cambia el resultado.' },
      { title: 'Aprovechar lo que se repite', text: 'Prefix caching ayuda si varias peticiones comparten un prefijo. Chunked prefill corta prompts largos para intercalarlos con decode. CUDA graphs pueden reducir overhead de lanzamiento a cambio de memoria adicional.' },
    ],
    notebook: 'Notebook 06 · Cambiar uno o dos ajustes y comparar con la línea base',
  },
  {
    id: '09', stage: 'produccion', title: 'Servir el modelo en producción', short: 'Operar en producción', visual: 'production',
    storyHeading: 'El servicio alrededor del modelo',
    lead: 'La GPU genera tokens. El servicio tiene que seguir funcionando cuando una réplica falla o llega otra versión.',
    idea: 'Clientes → API gateway → servicio IA → router → réplicas vLLM → GPU(s).',
    points: ['Una réplica está lista después de cargar y calentar el modelo, no al arrancar el proceso.', 'La cola, la salud y el tiempo de arranque importan para escalar.', 'La seguridad, las versiones y el coste forman parte del servicio.'],
    story: [
      { title: 'Antes de enviar tráfico', text: 'Comprueba salud y readiness después de cargar el modelo y hacer warmup. Mantén réplicas para alta disponibilidad; despliega versiones de forma gradual y prepara rollback.' },
      { title: 'Escalar lleva tiempo', text: 'Escalado vertical da más recursos a una réplica; horizontal añade réplicas. El scheduler de GPU y la cola importan. Arrancar una nueva instancia puede requerir descargar pesos, reservar memoria y calentar kernels: el autoscaling no es instantáneo.' },
      { title: 'Operar también es observar y proteger', text: 'Registra TTFT, latencia, throughput, tokens, cola, errores, solicitudes activas, VRAM, uso de GPU y coste. Prometheus/Grafana y OpenTelemetry son opciones para métricas y trazas. Aplica autenticación, autorización, cuotas, límites de tasa, gestión de claves, aislamiento y auditoría. Los prompts pueden contener datos sensibles: decide con cuidado qué registrar.' },
      { title: 'Cambiar sin cruzar los dedos', text: 'El router puede elegir modelo, versión y réplica. Evalúa antes del despliegue; usa canary o A/B si el caso lo justifica. Compara coste por solicitud terminada o token de salida bajo la misma calidad y SLO, incluyendo GPU reservadas sin trabajo. Kubernetes puede ayudar a desplegarlo, pero no es obligatorio.' },
    ],
  },
  {
    id: '10', stage: 'produccion', title: 'Paralelismo en varias GPU', short: 'Paralelismo multi-GPU', visual: 'parallel',
    storyHeading: 'Qué repartir y por qué',
    lead: 'Antes de repartir un modelo, pregunta qué se ha quedado corto: memoria, cálculo, contexto o capacidad de atender usuarios.',
    idea: 'TP, PP, DP, EP y CP reparten trabajos diferentes. La comunicación también cuesta.',
    points: ['TP divide operaciones dentro de capas; PP reparte capas entre etapas.', 'DP crea réplicas para peticiones distintas. EP distribuye expertos MoE.', 'CP distribuye trabajo o estado de atención para contextos largos, según soporte.'],
    story: [
      { title: 'Cuando el modelo no cabe en una GPU', text: 'Tensor Parallelism divide operaciones tensoriales de una capa y exige comunicación frecuente. Pipeline Parallelism reparte grupos de capas; las activaciones pasan entre etapas y pueden aparecer burbujas.' },
      { title: 'Cuando el problema son las peticiones', text: 'Data Parallelism ejecuta réplicas independientes. Cada una necesita memoria suficiente para su modelo o su propio grupo multi-GPU. Añadir réplicas no reduce el tamaño del modelo por réplica.' },
      { title: 'Expertos y contexto largo', text: 'Expert Parallelism reparte expertos MoE y mueve tokens hacia los elegidos. Context Parallelism divide trabajo o estado de atención de contextos largos; prefill y decode pueden requerir estrategias distintas. El soporte depende del modelo, backend y versión.' },
      { title: 'La topología decide parte del coste', text: 'Mover datos por NVLink, PCIe o red no cuesta lo mismo. Un reparto que parece perfecto en papel puede perder tiempo coordinando GPU. Nunca cuentes con una aceleración lineal sin medir.' },
    ],
    notebook: 'Notebook 07 · Demo guiada: TP=2 y EP si el hardware lo permite',
    footnote: 'Si no hay varias GPU para cada asistente, esta parte queda como demostración de los ponentes.',
  },
  {
    id: '11', stage: 'produccion', title: 'Ejercicio final: dimensionar', short: 'Dimensionar juntos', visual: 'sizing',
    storyHeading: 'Una decisión que exige medidas',
    lead: 'Tenemos un modelo de unos 14B, una GPU de 24 GB y usuarios concurrentes. Aún no sabemos si el servicio cumple.',
    idea: 'Una hipótesis de despliegue solo vale cuando pasa calidad, latencia, errores y memoria.',
    points: ['Supuestos hipotéticos: 8 solicitudes activas, 2.048 tokens de entrada y hasta 512 de salida por solicitud.', 'Objetivo didáctico: TTFT p95 por debajo de 2 s y errores inferiores al 1 %.', 'La configuración propuesta no está benchmarkeada.'],
    story: [
      { title: 'Primero, la cuenta ideal de pesos', text: 'FP16/BF16 rondan 28 GB: ya superan la tarjeta de 24 GB antes de cargar el runtime. INT8 ronda 14 GB; INT4, 7 GB. Esas dos últimas cifras tampoco demuestran que el modelo quepa ni que cumpla el TTFT.' },
      { title: 'Lo que falta saber', text: 'Necesitamos arquitectura y licencia del checkpoint, capas y KV heads para estimar la caché, soporte de la cuantización en la GPU, longitudes reales y comportamiento del runtime. Después toca medir calidad, errores, p95 y margen de VRAM.' },
      { title: 'Una hipótesis para empezar a medir', text: 'Probar un checkpoint cuantizado compatible, max-model-len 4096 y gpu-memory-utilization 0.85. Hacer pruebas con 1, 4 y 8 solicitudes activas. Son valores de partida, no una capacidad validada.' },
      { title: 'Si falla, cambia la pregunta', text: 'Si no cabe, estudia otra precisión o TP/PP. Si cabe pero no atiende suficiente trabajo, prueba réplicas DP. En producción añade router, readiness, límites, autenticación, métricas, evaluación de versión y rollback.' },
    ],
    decisions: [
      'Verificar arquitectura y licencia del checkpoint.',
      'Calcular el peso ideal en FP16/BF16, INT8 e INT4.',
      'Estimar la KV cache con el contexto y la concurrencia previstos.',
      'Elegir contexto, runtime y primeros ajustes que probar.',
      'Definir la prueba de carga y las métricas que decidirán.',
      'Decidir cuándo hacen falta otra GPU, TP/PP o réplicas DP.',
      'Añadir controles de producción y observabilidad.',
    ],
  },
];

export const sectionById = Object.fromEntries(sections.map(section => [section.id, section]));
